### ISSUE TITLE
Concatenate 2 or more matches in template fields

### ISSUE THREAD

**Issue by scotthansonde** [invoice-x/invoice2data#106]
I have a vendor that puts a decimal point in the middle of their invoice numbers. I'd like to be able to return the invoice number without the decimal point by matching something like
`invoice_number: BelegNummer:*(\d+)\.(\d+)`
and concatenating the two matches.

I was able to implement this locally with a one line change, but I don't really know python so I'm not sure this is a good change. :-)

```diff --git a/invoice2data/extract/invoice_template.py b/invoice2data/extract/invoice_template.py
index 7e0578b..df4aba0 100644
--- a/invoice2data/extract/invoice_template.py
+++ b/invoice2data/extract/invoice_template.py
@@ -158,7 +158,7 @@ class InvoiceTemplate(OrderedDict):
                     elif k.startswith('amount'):
                         output[k] = self.parse_number(res_find[0])
                     else:
-                        output[k] = res_find[0]
+                        output[k] = ''.join(res_find[0])
                 else:
                     logger.warning("regexp for field %s didn't match", k)
```

**Comment by m3nu** [comment]
That's a very specialized case, but the change may still be useful for other situations. Let me test for issues and then merge.

**Comment by m3nu** [comment]
You can probably solve this by changing the regex group a little bit. Like: 

`invoice_number: BelegNummer:*(\d+\.\d+)`

This will capture both parts plus the dot.

**Comment by bosd** [comment]
Option 1:
Since https://github.com/invoice-x/invoice2data/pull/487
It is possible to concatenate multple capturing groups.



Option2:
rewrite the line with the replacement feature.
```
options:
  replace:
    - ['(?P<field_start>BelegNummer:*)(?P<first_part>\d+)\.(?P<second_part>\d+)',' \g<field_start>\g<first_part>\g<second_part>']
```



Option 3:
Data cleansing post processing.
If one only wants to capture digits. 
A post processing could be done like:
`re.sub(r'\W+', '', invoice_number)`

This is not implemented in this lib yet.
But I use this in another module which calls invoice2data.

I see more use cases for this option. It would also help the use case of GfxKai.
But for now we only have the other 2 options. 
Will create a separate issue for the implementation of data sanitization after a match.
