### ISSUE TITLE
Regex result in group instead of match string

### ISSUE THREAD

**Issue by akashjobanputra** [invoice-x/invoice2data#125]
RegEx: 
```regex 
'\$\d+(,\d+)+'
```
RegEx result using ```import re```
```python
In [3]: res = re.search('\$\d+(,\d+)+', 'Dollars$1,035,000.00.')
In [4]: res
Out[4]: <_sre.SRE_Match object; span=(7, 17), match='$1,035,000'>
In [5]: res.groups()
Out[5]: (',000',)
```
Result from YAML-template:
```
DEBUG:root:field=amount | regexp=Dollars\$\d+(,\d+)+
DEBUG:root:res_find=[',000']
```
Result from invoice2data is the first group from the matched string, instead of entire match string. And last time I checked multiple groups were not supported yet.

**UPDATE**:
I noticed the function used is re.findall() which returns the matched group.
[invoice2data/invoice2data/extract/invoice_template.py#L174](https://github.com/m3nu/invoice2data/blob/086a1e021870ab1dba0d2e605b1b627021a19642/invoice2data/extract/invoice_template.py#L174)

**Comment by m3nu** [comment]
I guess we just return the first match and don't take capturing groups into account currently.

Any specific question or request you have here?

**Comment by m3nu** [comment]
One reason is that the same value could appear multiple times. so we only take the first match.

Beyond that the regex has 2 purposes: find the right place, getting specific data. You will never want to return everything. Like the label.

What would be your desired behavior? Concat all groups if more than one is found? We can never return the whole match because it would include the label. But I'm open to merging multiple groups. Your example isn't clear on that. Why not just expand your group to cover the whole number string? We remove commas automatically anyways. `Dollars\$\d+(,\d+)+`
