### ISSUE TITLE
Elis support

### ISSUE THREAD

**Issue by pasky** [invoice-x/invoice2data#148]
Would it make sense to also allow querying online APIs for invoice data capture, as an alternative to the template matching method?

Of course, there are typically commercial ones - the first on my mind would be Rossum Elis (the data extractor), which has open registration and a free monthly quota (and I'm affiliated with Rossum :) ). Though it would be worth making this modular obviously, as it's likely other APIs will go public in the future (e.g. infrrd OCR or the SMACC extractor).

We might be able to contribute the MR ourselves, just clearing whether this would be useful and acceptable (or, maybe, there would be a different component within invoice-x where this would fit better?)

**Comment by m3nu** [comment]
If developers use your service for data extraction it will be easier for them to integrate their workflow directly instead of using the `invoice2data` package. The only tasks left to do are opening and submitting files. I wouldn't want another dependency just for that.

With that being said, I would still be open to adding and maintaining an API wrapper for your [invoice extraction API](https://rossumrir.docs.apiary.io/#) to extend the ecosystem and have an alternative to template-based methods. Saving the result of your API as XML file using the Factur-X standard could be useful as well. That would also prepare adding it to the Odoo ERP system, which would in turn drive adoption with real customers.

Of course we would need strong assurances that the free developer tier stays in place for the next X years before considering this further. See the recent change to Google's Maps API as an example where such a dependency went downhill quickly.

**Comment by pasky** [comment]
You are right that the overlap with invoice2data is not so big. But having that API wrapper would make a lot of sense, I think.

I understand why you are wary whether the API is going to stay - this is always an issue with SaaS services, and I'm indeed not ready to promise that it is 100% certain to stay in this form and free in the developer tier for the next 10 years. However, I'd say that it is extremely unlikely we would be dropping the free developer tier in the coming years - in fact, all our plans and evidence so far point at actually rather raising the free quota in the future.  Hopefully, the high accuracy of the API compensates well for any uncertainty. :)

**Comment by m3nu** [comment]
Let's see. We'll wrap up the XML embedding first. Then look into adding your AI API. Thanks again for bringing it up.

**Comment by m3nu** [comment]
Closing. If this is done, it will be as a new project.
