### ISSUE TITLE
Tesseract fopenReadStream error

### ISSUE THREAD

**Issue by mnandesss** [invoice-x/invoice2data#220]
Hi,
I try to use invoice2data on a mac machine, and after installing it all, I got this error

```
invoice2data --debug --input-reader tesseract ~/Desktop/oyo.png 
Error in fopenReadStream: file not found
Error in pixRead: image file not found: Version: ImageMagick 7.0.8-33 Q16 x86_64 2019-03-13 https://imagemagick.org
Image file Version: ImageMagick 7.0.8-33 Q16 x86_64 2019-03-13 https://imagemagick.org cannot be read!
Error during processing.
DEBUG:invoice2data.main:START pdftotext result ===========================
DEBUG:invoice2data.main:
DEBUG:invoice2data.main:END pdftotext result =============================
DEBUG:invoice2data.main:Testing 109 template files
ERROR:invoice2data.main:No template for /Users/marcpuigdellivol/Desktop/oyo.png
```

However, if I run `tesseract ~/Desktop/oyo.png  out` it works and creates the out.txt file with all the text recognized,

any help on how to make it work?

Thank you!

**Comment by Gsuz** [comment]
This can be fixed by removing "shell=True" from line 29 of file tesseract.py

**Comment by Gsuz** [comment]
> This can be fixed by removing "shell=True" from line 29 of file tesseract.py

while this fixes the issue on Mac it causes another issue on Linux

**Comment by thenaturalist** [comment]
@m3nu does it make any sense to have `shell=True` in the code? The docs read like it is unnecessary on Windows and the current implementation is incompatible to  POSIX machines. Plus it opens the potential for shell injection. Happy to open a PR.

From the [subprocess.Popen docs](https://docs.python.org/3.7/library/subprocess.html#subprocess.Popen):
On Windows, if args is a sequence, it will be converted to a string in a manner described in Converting an argument sequence to a string on Windows. This is because the underlying `CreateProcess()`operates on strings.

The shell argument (which defaults to False) specifies whether to use the shell as the program to execute. If shell is True, it is recommended to pass args as a string rather than as a sequence.

On POSIX with `shell=True`, the shell defaults to `/bin/sh`. If args is a string, the string specifies the command to execute through the shell. This means that the string must be formatted exactly as it would be when typed at the shell prompt. This includes, for example, quoting or backslash escaping filenames with spaces in them. If args is a sequence, the first item specifies the command string, and any additional items will be treated as additional arguments to the shell itself. That is to say, Popen does the equivalent of:

`Popen(['/bin/sh', '-c', args[0], args[1], ...])`

On Windows with `shell=True`, the COMSPEC environment variable specifies the default shell. The only time you need to specify `shell=True` on Windows is when the command you wish to execute is built into the shell (e.g. dir or copy). You do not need shell=True to run a batch file or console-based executable.

**Comment by m3nu** [comment]
If everything keeps working without `shell=True`, feel free to remove it.
