### ISSUE TITLE
Invoice with multiple pages

### ISSUE THREAD

**Issue by schmidtkropp** [invoice-x/invoice2data#271]
Hello everybody,
I would like to use invoice2data for a small workaround with our accounting software.

I have a lot of invoices that span several pages. Unfortunately, the text is only used on the first page.
The invoices are scanned and then evaluated via tessercast:

invoice2data --input-reader tesseract /srv/kicArchiv_2020-01-142.pdf --template-folder / srv / templates --debug

Unfortunately, it often happens that the invoice amount is then on the second or third page.

**Comment by m3nu** [comment]
It should work for multiple pages. The German Qualityhosting template was developed for multiple pages IIRC.

It's possible that Tesseract only does the first page. In that case it's just a setting and could be changed with small adjustments.

**Comment by schmidtkropp** [comment]
Hello m3nu,

many thanks for the answer.
Can you describe the adjustments for Tessercast in more detail?

**Comment by Twister42** [comment]
Unfortunately invoice2data convert PDF to images using the PNG format which do not handle multi pages. If you want to do multi page on PDF you have to change to code by yourself and use TIFF format : in tesseract.py line 37 : png -> tiff

It works fine for me. Looking at the comments in the file it seems they used tiff in the past but switched to png. don't know why...

**Comment by bosd** [comment]
If i remember, previously the ghostscript engine was used for conversion.
Due to some security issues, the conversion was disabled, users had to bypass these rules.

I think it is fixed now with the current png implementation.
Now internally all the pages are added in one big png.
From experience png delivers as good as result then tiff files.
Hence, smaller file size, no security issues, works out of the box.
