### ISSUE TITLE
Debugging a template file is too difficult

### ISSUE THREAD

**Issue by reikred** [invoice-x/invoice2data#339]
Alright, I'm going to vent a bit here: I have been an occasional user of i2d for a few months now, and I find that template development is really difficult.  Here are some of the difficulties I run into:

1. When there is an error, I just get a stack dump. No name of the template file used, no line number for the template file, no line number for the data file (if a runtime error rather than a parse error), no offending regex, nothing. More info really is needed. Debugging this stuff is a hard for me as debugging elisp :-).

2. In other words, I can't even tell which template file and variable or line or regex in the template file is the offending entity

3. The TUTORIAL.md is fairly incomprehensible and in my view is not written well (say, compared to a GNU manual or similar).  I do not gain any insight into how the program designer was thinking, which is usually the key to understanding how to use a   program properly. When I read this "issues" forum, I see a lot of allusions to the correspondence between template syntax and various internal data structures of the program, but my understanding is lacking. Maybe I should not need to understand, but because the error messages are so cryptic I am grasping for a way to understand syntax and semantics.

4.  The --debug flag just dumps the pdftotext (or equivalent) to stderr, it does not appear to provide any other useful debug output. 

I freely admit that I am not a good python hacker, but as an experienced linux user, decently versed in regexp, and an occasional scripter/programmer , I thought I would understand SOMETHING from the error messages, but generally I do not. For example, what on earth am I supposed to understand from the following error message?

% invoice2data --template-folder ./tpl 86435364.pdf
Traceback (most recent call last):
  File "/usr/local/bin/invoice2data", line 11, in <module>
    load_entry_point('invoice2data', 'console_scripts', 'invoice2data')()
  File "/home/reikred/src/invoice2data/src/invoice2data/main.py", line 211, in main
    res = extract_data(f.name, templates=templates, input_module=input_module)
  File "/home/reikred/src/invoice2data/src/invoice2data/main.py", line 94, in extract_data
    return t.extract(optimized_str)
  File "/home/reikred/src/invoice2data/src/invoice2data/extract/invoice_template.py", line 178, in extract
    res_find = re.findall(v, optimized_str)
  File "/usr/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib/python3.8/re.py", line 294, in _compile
    return _cache[type(pattern), pattern, flags]
TypeError: unhashable type: 'collections.OrderedDict'

If anyone could write up some ideas on how to do a basic debugging or stepwise refinement of a template file, I think that would help. Maybe start with the simplest possible template file that does essentially nothing (just fake "static" values for the 4 required variables) ,and then do a stepwise refinement, and ALWAYS show along with the each step the data that it is supposed to parse.

Stepping off my soapbox.

**Comment by RossK1** [comment]
Agreed, a step-by-step guide with a sample invoice would be a great addition. If you supply an invoice (I don't want to scrub sensitive info out of all the ones I have 😋 ), I'll try find time to work on the guide itself.
I run this package exclusively in a python script, and with logging set to debug, I can see quite a bit of detail. It shows the original extracted text, the template it matched to (if any), the optimized text and which fields it is trying to process. Do you see any of that info?
For that specific error, it is the re package that is complaining. It is trying to execute `re.findall(v, optimized_str)` and v is a dictionary, not a string, hence `TypeError: unhashable type: 'collections.OrderedDict'`. This typically happens when there is an indentation issue in the template.

**Comment by reikred** [comment]
@RossK1, I'm working on santizing an invoice pdf that you can use as an example for a tutorial! Thanks for taking an interest.

**Comment by rmilecki** [comment]
> File "/home/reikred/src/invoice2data/src/invoice2data/extract/invoice_template.py", line 178, in extract
> res_find = re.findall(v, optimized_str)

This particular error was caused by using **new** field syntax with **old** version of `invoice2data`. I suppose you had something like:
```
fields:
  foo:
    parser: static
    value: 10
```
in your template. Old versions of `invoice2data` required every `fields` entry to be a single string or list of strings. In both cases string(s) were treated as regexes.

**Comment by rmilecki** [comment]
@reikred: `invoice2data`'s output was significantly improved since your report. Warning and errors are always displayed. The most important info as well. You can also run with `-d` to enable debugging message. I believe we can mark it as solved now.
