### ISSUE TITLE
cannot support tesseract

### ISSUE THREAD

**Issue by Jane-Ding** [invoice-x/invoice2data#345]
Hi, I want to use tesseract to extract text from pdf/image, but it throws the error:

Invalid Parameter - 350
Error during processing.
ERROR:invoice2data.main:No template for AWS_invoice.pdf

I can successfully parse the aws invoice with pdftotext.

**Comment by hafwil** [comment]
Hi!
First of all many thanks to team of invoice2data for this great tool!

I had the same issue on windows.
On windows make sure to install ghostscript, imagemagick and tesseract binaries.
The problem is that there is a "convert.exe" in system32 folder and the system32 might be resolved before your imagemagick path.
Since the convert tool from imagemagick is legacy, the input/tesseract.py module should call "magick" and not "convert".

best regards, wil

**Comment by bosd** [comment]
> Since the convert tool from imagemagick is legacy, the input/tesseract.py module should call "magick" and not "convert".

I've looked into this. Sadly the magick command is not yet fully supported. This module is used as a library on a lot of debian systems. I believe they don't support the magick command yet. So better to change this in the future when magick is more adopted.
