### ISSUE TITLE
0.4.0 release

### ISSUE THREAD

**Issue by m3nu** [invoice-x/invoice2data#400]
I suggest we do a major version release, after you're done with your changes, @bosd.

Will do it myself and document the steps better. Basically it's adding a tag and uploading to PyPi. Then add you as member on PyPi and admin here on Github.

Comment here, when it's ready. Also recommend using the milestone feature to categorize issues.

**Comment by rmilecki** [comment]
I'll review some of pending pull requests this weekend.

**Comment by bosd** [comment]
> I'll review some of pending pull requests this weekend.

@rmilecki 
Thanks,
Currently struggling with the tests.
And the output of pdfminer.

**Comment by bosd** [comment]
@rmilecki @m3nu 
Would it be possible to challenge ourselves to do the new major release this monday?

I know it is huge challenge, with the current open pr's for review. But it would be awesome, if we could get it done. So the result can be presented at an event i'm attending next week 🙏

**Comment by m3nu** [comment]
I can help publish it on PyPi after it's tagged. Just update us on the progress here.

**Comment by bosd** [comment]
@m3nu 
I would say its time for the release. :fireworks: 🍾 
There is so much more I wanted to get in. 
But the reality is, the pace of development has gone down.
Due to attention needed on other projects.

Waiting untill all my ideas are in code, would mean an even further delay of a new release.
There are already so much new features.
So it's worthwhile to release it. We can always do incremental improvements from here on.

**Comment by m3nu** [comment]
Will do!

**Comment by bosd** [comment]
@m3nu Friendly reminder 😃

**Comment by m3nu** [comment]
Done!

https://pypi.org/project/invoice2data/0.4.0/

Also happy to add @rmilecki  and yourself to PyPi as collaborator, so you can manage releases there. Just need your username there.
